---
title: "Workflow (reporttool)"
author: "Kristian D. Olsen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## About

This package is meant for a particular use, which is to work with data from surveys to generate batch reports. To do so, we need to keep track of the labels (questions) for each variable, in addition to latent associations for use in structural modelling (PLS-PM).

To achieve this, `reporttool` provides a `Survey` class which is built using R6, and stuffs some extra information into private (hidden) `fields` inside it. For users, a `Survey` should look and behave pretty much like a normal `data.frame`, `data.table` or `tbl` (dplyr). Internally `Survey`'s helps us keep track of the hidden fields, toward the end goal of automating tables, plots and reports.

*Note* that `reporttool` is meant to be used with `officeR` and `tabulR`.

## Usage

As an example, let's take some "raw data" from SPSS and complete a Survey to generate various output. I recommend using dplyr, which will be used for this example.

#### Read and prepare

```{r}
require(dplyr)
require(officeR)
require(tabulR)
require(reporttoolDT)

sav <- read_data(system.file("extdata", "raw_data.sav", package = "reporttoolDT"))
srv <- survey_tbl(sav) %>%
  set_association(common = TRUE) %>%
  set_config(name = "Example", segment = "B2C", cutoff = .3) %>%
  set_marketshare(CompanyA = .3, CompanyB = .5, CompanyC = .2) %>%
  set_translation(language = "english") %>%
  latents_mean() %>%
  set_label(auto = TRUE)
```

